name: Endrex
author: nahkd123
description: Add stuffs for the boring The End
main: me.nahkd.spigot.sfaddons.endrex.Endrex
website: https://github.com/nahkd123/Endrex
depend: ["Slimefun"]
softdepends:
- "BentoBox"                 # Load after the BentoBox plugin is loaded. Why? Because sometimes Endrex load before
                             # BentoBox, which cause NPE
version: ${project.version}
api-version: "1.16"
